export type CheckFinanceRows = {
  edit: string;
  id?: string;
  code?: string;
  checkDate: string;
  transactionDate: Date;
  firm: string;
  amount: number;
  checkNo: string;
  description: string;
  status: string;
  type: string;
  bankCode: string;
  transactionid: string;
  projectid: string;
  companyid: string;
  createdby: string;
  updatedby: string;
  createdatetime: Date;
  updatedatetime: Date;
};
