import {
  LayoutDashboard,
  Layers,
  HandCoins,
  Coins,
  BanknoteArrowDown,
  Landmark,
  TicketCheck,
  NotepadText,
  TicketPercent,
  Truck,
  UsersRound,
  UserRoundCog,
  Building2,
  NotebookText,
  RulerDimensionLine,
  ArrowBigLeftDash,
  IdCardLanyard,
  FileUser,
} from "lucide-react";
import { PagesMenuItemType } from "../../types/menu/PagesMenu";

export const PageMenuItems = (projectId?: string): PagesMenuItemType[] => {
  const basePath = projectId ? `/project/${projectId}` : "";

  return [
    {
      label: "Genel Bakış",
      href: projectId ? `${basePath}/dashboard` : "admin-dashboard",
      icon: LayoutDashboard,
      portalYN: false,
      adminYN: !projectId,
      employeeYN: false,
    },
    {
      label: "Satışlar",
      href: `${basePath}/sales`,
      icon: NotepadText,
      portalYN: false,
      adminYN: false,
      employeeYN: false,
    },
    {
      label: "Stok Durumu",
      href: "/stock",
      icon: Layers,
      portalYN: false,
      adminYN: false,
      employeeYN: false,
    },
    {
      label: "Stok Durumu",
      href: projectId ? `/stock` : "stock",
      icon: Layers,
      portalYN: false,
      adminYN: true,
      employeeYN: false,
    },
    {
      label: "Tedarik",
      href: `${basePath}/supply`,
      icon: Truck,
      portalYN: false,
      adminYN: false,
      employeeYN: false,
    },
    {
      label: "Taşeron",
      href: `${basePath}/subcontractor`,
      icon: UsersRound,
      portalYN: false,
      adminYN: false,
      employeeYN: false,
    },
    {
      label: "Cari",
      href: `/current`,
      icon: HandCoins,
      portalYN: false,
      adminYN: true,
      employeeYN: false,
    },
    {
      label: "Ödeme Ekle",
      href: "/company-finance",
      icon: BanknoteArrowDown,
      portalYN: false,
      adminYN: true,
      employeeYN: false,
    },
    {
      label: "Çek Ekle",
      href: "/check-finance",
      icon: TicketCheck,
      portalYN: false,
      adminYN: true,
      employeeYN: false,
    },
    {
      label: "Krediler",
      href: "/loans",
      icon: Landmark,
      portalYN: false,
      adminYN: true,
      employeeYN: false,
    },
    {
      label: "Nakit Akış",
      href: "/cash-flow",
      icon: Coins,
      portalYN: false,
      adminYN: true,
      employeeYN: false,
    },
    {
      label: "Satışlar",
      href: "/sales",
      icon: NotepadText,
      portalYN: false,
      adminYN: true,
      employeeYN: false,
    },
    {
      label: "Hesap Bakiyeleri",
      href: "/balances",
      icon: TicketPercent,
      portalYN: false,
      adminYN: true,
      employeeYN: false,
    },
    {
      label: "Banka Hareketleri",
      href: "/bank-movement",
      icon: TicketPercent,
      portalYN: false,
      adminYN: true,
      employeeYN: false,
    },
    {
      label: "Projeler",
      href: "/projects",
      icon: Building2,
      portalYN: false,
      adminYN: true,
      employeeYN: false,
    },
    {
      label: "Taşeron Listesi",
      href: "/subcontractor-list",
      icon: UsersRound,
      portalYN: false,
      adminYN: true,
      employeeYN: false,
    },
    {
      label: "Tedarikçi Listesi",
      href: "/supplier-list",
      icon: Truck,
      portalYN: false,
      adminYN: true,
      employeeYN: false,
    },
    {
      label: "Metraj",
      href: `${basePath}/quantity`,
      icon: RulerDimensionLine,
      portalYN: false,
      adminYN: false,
      employeeYN: false,
    },
    {
      label: "Maliyet Özeti",
      href: `${basePath}/cost-summary`,
      icon: NotebookText,
      portalYN: false,
      adminYN: false,
      employeeYN: false,
    },
    {
      label: "Personel Yönetim",
      href: "/employees-portal/dashboard",
      icon: UserRoundCog,
      adminYN: true,
      portalYN: true,
      employeeYN: false,
    },
    {
      label: "Personeller",
      href: "/employees-portal/employees",
      icon: IdCardLanyard,
      adminYN: false,
      portalYN: false,
      employeeYN: true,
    },
    {
      label: "Yıllık İzin",
      href: "/employees-portal/annual-leave",
      icon: FileUser,
      adminYN: false,
      portalYN: false,
      employeeYN: true,
    },
    {
      label: "Admin Genel Bakış",
      href: "/admin-dashboard",
      icon: ArrowBigLeftDash,
      portalYN: false,
      adminYN: false,
      employeeYN: false,
    },
    {
      label: "Admin Genel Bakış",
      href: "/admin-dashboard",
      icon: ArrowBigLeftDash,
      portalYN: false,
      adminYN: false,
      employeeYN: true,
    },
  ];
};
